# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://livdipe.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
# username: Lorem Ipsum
username: lividpe 
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Anon Developer
email: livdipe@gmail.com
twitter_username: livdipe
github_username:  livdipe
gplus_username:  livdipe
disqus_username: livdipe

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
